### ISSUE TITLE
Error creating notes

### ISSUE THREAD

**Issue by paternogbc** [seanh/terminal_velocity#44]
Hi,

I just installed your app in my computer (running Ubuntu 14.04 LTS, 64 bits).
However, when I lunch the app and try to creat any note I get this error:

> Traceback (most recent call last):
  File "/usr/local/bin/terminal_velocity", line 116, in <module>
    main()
  File "/usr/local/bin/terminal_velocity", line 110, in main
    extension=args.extension, extensions=args.extensions)
  File "/usr/local/lib/python2.7/dist-packages/terminal_velocity/urwid_ui.py", line 444, in launch
    loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 272, in run
    self.screen.run_wrapper(self._run)
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 242, in run_wrapper
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 337, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 708, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 787, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 388, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 488, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/terminal_velocity/urwid_ui.py", line 332, in keypress
    system(self.editor, [note.abspath], self.loop)
  File "/usr/local/lib/python2.7/dist-packages/terminal_velocity/urwid_ui.py", line 41, in system
    raise e
OSError: [Errno 2] Arquivo ou diretório não encontrado

The note is created but I cant see or do any thing with it.
Any suggestion?

Thanks in advance!

**Comment by seanh** [comment]
> Arquivo ou diretório não encontrado

Translation: File or directory not found. @paternogbc I'm not sure, is your notes directory missing or something?

**Comment by paternogbc** [comment]
Hi @seanh,
I have created the directory, the notes are also created ("blank file"), is just that the app crash when I hit enter to create or edit any note. And then it gives the error message described above. 

I will do more tests and let you know. If you need more information about my system, please let me know, I will be happy to provide.
Cheers

**Comment by paternogbc** [comment]
Hi @seanh, It is now fixed, it was not related to the directory.

Was a problem with my vim instalation. After removing and instaling vim, terminal velocity started to work just fine. =) No more errors. 

All the best and thanks for this great app! 
Gustavo

**Comment by seanh** [comment]
Awesome! Glad you like it. Your traceback _does_ show a bug in Terminal Velocity, even if there was something wrong with your vim tv shouldn't crash like that, but since I don't know exactly what the bug is I'll close this for now,
