### ISSUE TITLE
Not working after upgrading to big sur.

### ISSUE THREAD

**Issue by loveslap** [seanh/terminal_velocity#50]
Traceback (most recent call last):
  File "/usr/local/bin/terminal_velocity", line 129, in <module>
    main()
  File "/usr/local/bin/terminal_velocity", line 123, in main
    exclude=args.exclude)
  File "/usr/local/lib/python2.7/site-packages/terminal_velocity/urwid_ui.py", line 442, in launch
    loop.run()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 272, in run
    self.screen.run_wrapper(self._run)
  File "/usr/local/lib/python2.7/site-packages/urwid/raw_display.py", line 242, in run_wrapper
    return fn()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 312, in _run
    self.draw_screen()
  File "/usr/local/lib/python2.7/site-packages/urwid/main_loop.py", line 563, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/site-packages/urwid/container.py", line 1058, in render
    focus and self.focus_part == 'body')
  File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/site-packages/urwid/decoration.py", line 564, in render
    canv = self._original_widget.render((maxcol,)+size[1:], focus)
  File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/site-packages/terminal_velocity/urwid_ui.py", line 192, in render
    return super(NoteFilterListBox, self).render(size, self.fake_focus)
  File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/site-packages/urwid/listbox.py", line 487, in render
    canvas = widget.render((maxcol,))
  File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/site-packages/terminal_velocity/urwid_ui.py", line 80, in render
    canv = super(NoteWidget, self).render(size, focus=focus)
  File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/site-packages/urwid/widget.py", line 1008, in render
    return apply_text_layout(text, attr, trans, maxcol)
  File "/usr/local/lib/python2.7/site-packages/urwid/canvas.py", line 1291, in apply_text_layout
    text[s.offs:s.end])
  File "/usr/local/lib/python2.7/site-packages/urwid/util.py", line 121, in apply_target_encoding
    s = s.encode( _target_encoding )
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0301' in position 8: ordinal not in range(128)

**Comment by loveslap** [comment]
Word doc accidentally left in Notes folder caused this.
